name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: \${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: npm install
        run: |
          npm --prefix app install

      - name: npm test
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          npm --prefix app run package
          npm --prefix app run lint
          npm --prefix app exec tsc
          npm --prefix app test
